version: '3.1'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbadmin
      MYSQL_USER: cake
      MYSQL_PASSWORD: cake
      MYSQL_DATABASE: cake
    volumes:
      - "db_storage:/var/lib/mysql"
      - ${PWD}/docker/mariadb:/etc/mysql/conf.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=cake
      - PMA_PASSWORD=cake
    links:
      - db
    ports:
      - 8080:80
    volumes:
      - /sessions
    environment:
      - VIRTUAL_HOST=pma.local
  birota:
    image: cake3
    build: docker/php
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - "${PWD}:/var/www/html"
    depends_on:
      - db
    links:
      - db
    ports:
      - 10080:80
    environment:
      - VIRTUAL_HOST=birota.local
  cloud9:
    image: sshinya/alpine-cloud9
    volumes:
      - "${PWD}:/workspace"
    environment:
      - VIRTUAL_HOST=cloud9.local

volumes:
  db_storage:
